### ISSUE TITLE
io.EOF on db.Ping()

### ISSUE THREAD

**Issue by martinhpedersen** [VoltDB/voltdb-client-go#13]
I am unable to authenticate with our VoltDB 4.4 server using the ```database/sql``` driver.

Go code:
```go
package main

import (
	"database/sql"
	"log"

	_ "github.com/VoltDB/voltdb-client-go/voltdbclient"
)

func main() {
	db, err := sql.Open("voltdb", "nimel.srv:21212")
	if err != nil {
		log.Fatal("open error: ", err)
	}
	defer db.Close()

	if err := db.Ping(); err != nil {
		log.Fatal("ping error: ", err)
	}
}
```

Application output:
>```
>2016/08/25 10:01:30 ping error: EOF
>exit status 1
>```

VoltDB log:
>```
>2016-08-25 07:56:07,731   WARN  [Client authenticator - 13868] HOST: Exception authenticating and registering user in ClientAcceptor
>java.io.IOException: String length is bigger than total buffer 16777216
>        at org.voltdb.messaging.FastDeserializer.readString(FastDeserializer.java:194)
>        at org.voltdb.ClientInterface$ClientAcceptor.authenticate(ClientInterface.java:617)
>        at org.voltdb.ClientInterface$ClientAcceptor.access$300(ClientInterface.java:260)
>        at org.voltdb.ClientInterface$ClientAcceptor$AuthRunnable.run(ClientInterface.java:350)
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
>        at org.voltcore.utils.CoreUtils$4$1.run(CoreUtils.java:329)
>        at java.lang.Thread.run(Thread.java:745)
>```

------

Please also note that the io documentation discourages use of io.EOF to signal an unexpected EOF in a structured data stream:
> Functions should return EOF only to signal a graceful end of input. If the EOF occurs unexpectedly in a structured data stream, the appropriate error is either ErrUnexpectedEOF or some other error giving more detail.

**Comment by martinhpedersen** [comment]
After some more investigation I've discovered this difference between rbetts/voltdbgo and this package:
```
 func writeLoginMessage(writer io.Writer, buf *bytes.Buffer) {
        // length includes protocol version.
-       length := buf.Len() + 1
+       length := buf.Len() + 2
        var netmsg bytes.Buffer
        writeInt(&netmsg, int32(length))
        writeProtoVersion(&netmsg)
```

When changing the constant to 1 I am able to do db.Ping without the error.

Is this a protocol difference and incompatibility with older VoltDB versions? I can't find any mention of this incompatibility in the documentation.

If this is a protocol incompatibility issue, I would expect the error message to indicate a protocol version mismatch.

Thanks!

**Comment by martinhpedersen** [comment]
This seems to be related: https://github.com/rbetts/voltdbgo/issues/11

**Comment by miketex** [comment]
Hi Martin - yes this is a protocol difference and incompatibility with older versions of VoltDB.  I'll make the protocol version configurable and clean up the error message...  Thanks for the input.

**Comment by martinhpedersen** [comment]
Excellent!

I am really excited about this package and your decision to support Go officially. Thanks!

**Comment by miketex** [comment]
Hi Martin - I just pushed up a new version of the go client.  It supports older versions of VoltDB; there are comments in the voltdb-client-go/README.md file and in the driver_hello_world example.  This is a new version so there are many other changes as well.  Let me know if you have any issues or questions at all, I'd be glad for any feedback and happy to make any needed changes.  Thanks - Mike.

**Comment by martinhpedersen** [comment]
Thank you Mike - I just confirmed that the new version supports VoltDB 4.4 by setting `voltdbclient.ProtocolVersion = 0`. :+1: 

Over the next few months I will be migrating my company's VoltDB applications to use this package. I will keep you posted.

Thanks!

**Comment by martinhpedersen** [comment]
Cleaning up after myself, closing this issue now. Thanks!
