### ISSUE TITLE
Deserialization of TIMESTAMP

### ISSUE THREAD

**Issue by martinhpedersen** [VoltDB/voltdb-client-go#14]
When scanning a TIMESTAMP column, I get "Not supporting TIMESTAMP".

It seems like this is implemented  by `func VoltRows.GetTimestamp()`, but the func is never called in `func VoltRows.Next`. Is this something that is going to be fixed/supported in the near future?

Would you except a pull request?

**Comment by miketex** [comment]
Martin - yes, I will fix, shouldn't take long.  We would accept pull requests, I believe you need to do some paperwork first, fill out a CLA.  I'll look into that.  I think deserializing timestamp is pretty straightforward, though, I'll look at it now.  Thanks - Mike

**Comment by miketex** [comment]
Martin - I pushed up changes to support deserialization of timestamps.  Let me know if anything else comes up.  Also, let me know if you'd like me to send a CLA so that you can submit pull requests.  - Mike

**Comment by martinhpedersen** [comment]
Mike, thanks.

I've just tested these new changes. It works as I expected, except for `NULL TIMESTAMP`. I expected NULL to be scanned into a empty time.Time-struct (with `time.IsZero()` returning true), instead it scans into a `*time.Time <nil>`.

I don't believe we need to use a pointer to represent a `NULL TIMESTAMP`, because `time.Time` has the `IsZero` function/default state.

It seems like most other database/sql drivers (including lib/pq) provides a [NullTime](https://godoc.org/github.com/lib/pq#NullTime) type. I personally would prefer the simple `time.Time{}` and it's [`IsZero()`](https://golang.org/pkg/time/#Time.IsZero). It is simpler, and only downside is that you can't distinguish  January 1, year 1, 00:00:00 UTC from NULL.

----

Regarding CLA - I may as well sign the CLA, seeing that some of my contributions from github.com/rbetts/voltdbgo already have made it's way into this project already. :) Also, I would love to be able to contribute code. How do we do this? My email is public on github.

**Comment by miketex** [comment]
Hi Martin - I missed this comment somehow.  I'll look into the NULL TIMESTAMP as well as the CLA. - Mike

**Comment by abradley201** [comment]
Looks like miketex resolved this issue on September 9th, 2016:

https://github.com/VoltDB/voltdb-client-go/commit/e3f79944b806e072ebfdcd608d4180fb3332c871#diff-8fa9fcf37cdd2090a545afddae483a0cL351

Closing now.
