### ISSUE TITLE
Deserialization of empty STRING

### ISSUE THREAD

**Issue by martinhpedersen** [VoltDB/voltdb-client-go#17]
When scanning an empty STRING into a variable of type string I get the error:
>Scan error on column index 0: unsupported Scan, storing driver.Value type <nil> into type *string

It seems like the driver treats an empty STRING as a null STRING, trying to assign it `nil`.

Here is the code to reproduce:

```go
package main

import (
	"database/sql"
	"log"

	_ "github.com/VoltDB/voltdb-client-go/voltdbclient"
)

func main() {
	db, err := sql.Open("voltdb", "jorel.srv:21212")
	if err != nil {
		log.Fatal("open error: ", err)
	}
	defer db.Close()

	var str string
	err = db.QueryRow("@AdHoc", "select '' from dbstate").Scan(&str)
	if err != nil {
		log.Fatalf("Error scanning empty string: %s", err)
	}

	log.Printf("Got string of length %d", len(str))
}
```

Expected output:
> `2016/09/07 09:51:50 Got string of length 0`

Instead I get:
> ```
> 2016/09/07 09:51:59 Error scanning empty string: sql: Scan error on column index 0: unsupported Scan, storing driver.Value type <nil> into type *string
> exit status 1
> ```

**Comment by miketex** [comment]
Hi Martin - will take a look today and let you know... - Mike

**Comment by miketex** [comment]
Martin - I just pushed up the fix for this...  Sorry for the delay...

**Comment by martinhpedersen** [comment]
Excellent - thank you!
