### ISSUE TITLE
database/sql connections are never closed

### ISSUE THREAD

**Issue by disq** [VoltDB/voltdb-client-go#19]
database/sql connections seem to hang there (confirmed with `netstat -np | grep 21212`) for indefinite amount of time, even if db.SetMaxIdleConns/db.SetConnMaxLifetime are set.

The (simple `select count(1) from table where pk > 0`) queries are prepared with db.Prepare and then queried with stmt.Query(). *Rows and *DB objects are both closed afterwards.

**Comment by ppontryagin** [comment]
:+1: the same

**Comment by gernest** [comment]
Gentle ping @disq @ppontryagin 

I did investigate this issue, based on this commit 5326a1f8a3231e2cc875a969fa6f932f9cda3c00 . I was not able to reproduce the issue.

If you don't explicitly call `db.Close`, hey are closed when the program exits. You can control the number of open connections at any given time with `db. SetMaxOpenConns`

Calling `rows.Close` has no effect to the underlying connection.

**Comment by disq** [comment]
From what I understand, database/sql will attempt to close idle connections (or after the ConnMaxLifetime expires) but they are still left open on the driver side. I'm running a long-lived process so the program won't exit for a long time. Here's what I did to try and limit open connections: https://github.com/peakgames/sql-agent/commit/9f099bb5a1be135734ad4918c09611e6b5c97ead

**Comment by gernest** [comment]
@disq can you expand a bit. The snippet you linked is the one that doesn't work?

Regarding using `SetConnMaxLifetime` you set the time in which the connection can be reused.  And from the documentation it says `If d <= 0, connections are reused forever`

On your code snippet `db.SetConnMaxLifetime(0)` implies reuse the connections forever.

**Comment by disq** [comment]
The snippet I linked is the workaround/solution. If I leave that part out, it will leak connections every 10 minutes, which is the value passed to `SetConnMaxLifetime`.

**Comment by gernest** [comment]
I see, I wasn't able to reproduce this before. Let me try to reproduce  this again. I will Ping you if  I find something.

A few questions , just to help get more context

- Which version of the client did you use? . 
  This command can help retrieve it
  ```
  cd $GOPATH/src/github.com/VoltDB/voltdb-client-go&&git log --pretty=format:'%h' -n 1
  ```
Thanks

**Comment by gernest** [comment]
And if you can provide a simple test case that can reproduce this it will be highly appreciated.

**Comment by disq** [comment]
Looks like this is what we used: c745282128d36ea2b966b5530a252e75f7608c11 (it's already vendored in [peakgames/sql-agent](https://github.com/peakgames/sql-agent), `vendor/` dir)
I'll send a test case soon.

**Comment by gernest** [comment]
@disq thanks,

That is a very old  commit. Can you please try it with the latest master branch?

> I'll send a test case soon

No problem, I'm also assembling a test case now. I have a rough idea!

**Comment by disq** [comment]
Test case here: https://gist.github.com/disq/e6903684629077bb80afe40c5bcfb14f

**Comment by gernest** [comment]
Thanks. I will get back to you when I find something.

**Comment by gernest** [comment]
I was able to reproduce this. Here is a full script I used, instead of printing the matched connections I'm counting them with grep.

This script, counts the number of open connections every 2 seconds. 

`main.go`
```go
package main

import (
	"database/sql"
	"fmt"
	"io"
	"log"
	"os/exec"
	"time"

	"bytes"

	"strings"

	_ "github.com/VoltDB/voltdb-client-go/voltdbclient"
)

func main() {
	db, err := sql.Open("voltdb", "localhost:21212")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()
	db.SetMaxIdleConns(10)
	db.SetConnMaxLifetime(1 * time.Second)
	go func() {
		for {
			select {
			case <-time.After(2 * time.Second):
				netstat()
			}
		}
	}()
	stmt, err := db.Prepare("SELECT count(*) FROM foo ") // <-- insert table name here
	if err != nil {
		log.Fatal(err)
	}
	for {
		select {
		case <-time.After(time.Second):
			var dest int
			err = stmt.QueryRow().Scan(&dest)
			if err != nil {
				log.Fatal(err)
			}
		}

	}
}

func netstat() {
	a := exec.Command("netstat", "-n", "-p", "tcp")
	b := exec.Command("grep", "-c", "21212")
	r, w := io.Pipe()
	a.Stdout = w
	b.Stdin = r

	var buf bytes.Buffer
	b.Stdout = &buf
	a.Start()
	b.Start()
	a.Wait()
	w.Close()
	b.Wait()
	buf.UnreadRune()
	fmt.Println("==> ", strings.TrimSpace(buf.String())+" - connections")
}


```

We can observe the connections ballooning by running `go run main.go` . I got something like this

```shell
==>  4 - connections
==>  8 - connections
==>  14 - connections
==>  18 - connections
==>  22 - connections
==>  26 - connections
==>  28 - connections
==>  34 - connections
==>  38 - connections
==>  42 - connections
==>  46 - connections
==>  50 - connections
==>  54 - connections
==>  58 - connections
==>  62 - connections
==>  66 - connections
==>  70 - connections
==>  74 - connections
==>  78 - connections
==>  82 - connections
==>  86 - connections
==>  90 - connections
==>  94 - connections
==>  98 - connections
==>  102 - connections
==>  106 - connections
==>  110 - connections
==>  114 - connections
==>  118 - connections
==>  122 - connections
==>  126 - connections
==>  130 - connections
==>  134 - connections
==>  138 - connections
==>  142 - connections
==>  146 - connections
==>  150 - connections
==>  154 - connections
==>  158 - connections
```

This is a serious bug

@nshi  can we add a  Bug label to this?

**Comment by gernest** [comment]
Gentle ping @disq 

I have submitted the #30   with the fix.

 Running the same script produces the following.

```shell
==>  2 - connections
==>  2 - connections
==>  2 - connections
==>  0 - connections
==>  2 - connections
==>  2 - connections
==>  2 - connections
==>  2 - connections
==>  2 - connections
==>  2 - connections
==>  2 - connections
==>  2 - connections
==>  2 - connections
```

Which is the same as when you use `pq` the postgres database client and grep for the postgres port.
