### ISSUE TITLE
Is there an existing spec?

### ISSUE THREAD

**Issue by albertogg** [VoltDB/voltdb-client-go#2]
Hello, Is there's an existing spec of what every VoltDB client should have?

**Comment by benjaminballard** [comment]
Hi Albert,

We have a document that describes the wire protocol here: http://downloads.voltdb.com/documentation/wireprotocol.pdf

But there is no spec for what every client should have.  The existing clients that have the most features are the java and C++ clients, so those would be good places to look.  We're actively developing a fully-supported Go client, which will be here in this repo.  Are you interested in contributing to this in some way, or is there some other language you have in mind?

Best regards,
Ben

**Comment by albertogg** [comment]
Thanks, that's fine, I'll read the wire protocol. I'm interested in contributing to the Go client, but I don't know if you guys have a roadmap, or list of pending tasks.

**Comment by akhanzode** [comment]
Hi Albert,

We are working on initial/baseline checked in soon. If you want to contribute you will have to sign CLA which can be found here https://voltdb.com/contributor-license-agreement

**Comment by albertogg** [comment]
Thanks @akhanzode, no problem. Will sign the CLA.
