### ISSUE TITLE
How to use username and password in golang sql?

### ISSUE THREAD

**Issue by OceanW** [VoltDB/voltdb-client-go#43]
I setup a voltdb, where user name and password are operator and mech.
I can use sqlcmd --user=operator --password=mech to connect.

sql.Open("voltdb", "operator:mech@tcp(localhost:21212)")
This seems don't work.

What's the right way to specify the data source?

**Comment by nshi** [comment]
Hi @OceanW, I see that you have closed the issue. I hope you have found the solution to your question. If not, using the following should be able to connect and authenticate with VoltDB.

```go
db, err := sql.Open("voltdb", "voltdb://operator:mech@localhost")
```

**Comment by OceanW** [comment]
Yes, I found it in the driver source code. Thank you all the same.
