### ISSUE TITLE
How to use Procedure Invocation?

### ISSUE THREAD

**Issue by jannes-sa** [VoltDB/voltdb-client-go#45]
Hi VoltDB Team

I see in your code, you have put some invocation procedure to DB
can you please make a test file so i can see it more clearly

**Comment by abradley201** [comment]
Hey Jannes-sa. Thanks for your question.

The best example I see for procedure invocation can be found in the query_api here: https://github.com/VoltDB/voltdb-client-go/blob/6c183613d69c850b0b1480f12a165de27b21680f/voltdbclient/query_api.go#L26-L70

Both newSyncProcedureInvocation and newAsyncProcedureInvocation are used to create functions for querying the DB. Reading this code and comparing it to the actual functions here will hopefully help you to understand how it works:

https://github.com/VoltDB/voltdb-client-go/blob/6c183613d69c850b0b1480f12a165de27b21680f/voltdbclient/procedure_invocation.go#L39-L63
