### ISSUE TITLE
Hide connection credentials from error message

### ISSUE THREAD

**Issue by samtech09** [VoltDB/voltdb-client-go#61]
If any node is down, client raise error with complete connection string/url along with credentials. For example

`node voltdb://admin:1234567@192.168.1.2: is down`

It should just show host (i.e.192.168.1.2 in above example) instead of full connection string.

**Comment by dxvgef** [comment]
I hope so, but now I can only handle the error message myself, this library seems to be very inactive. 😟

**Comment by akhanzode** [comment]
Fixed.
