### ISSUE TITLE
How to configure TLS in the client

### ISSUE THREAD

**Issue by evilin13** [VoltDB/voltdb-client-go#63]
Hello,

I have enabled TLS on a VoltDB server and I would like to use the GO client.
In other clients (C++, Python) I can clearly see that SSL/TLS is supported, but in the GO client I cannot figure out how to configure TLS. 
If it is supported in the GO client too, then could you please share an example of how to configure it?

Thank you!

**Comment by benjaminballard** [comment]
This client doesn't currently support TLS. We don't have any plans at this time to add that, but if it's something you'd like to work on you can submit a Contributor License Agreement (https://www.voltdb.com/contributor-license-agreement/) and we can review pull requests.
